### ISSUE TITLE
Peer-Tracker Communication

### ISSUE THREAD

**Issue by BKDuncan** [paulchenpmc/codeCollab#8]
## Socket.io Message Design
An outline of what events we support and who works on it.

### Tracker-to-Peer
- [x] Connect
- [x] Disconnect
- [x] Send list of sessions to peer
- [x] Send Peer ID list for session to a peer
- [x] Send a document to peer

### Peer-to-Tracker
- [x] Connect
- [x] Disconnect
- [x] Start a session with empty doc
- [x] Start a session with existing doc (local)
- [x] Join a session with peers
- [x] Join a sesssion with no peers (persistent doc at the tracker)
- [ ] ~~Send heartbeat~~
- [x] Request list of docs/sessions
- [x] Backup tracker document
- [x] Send latest doc if last peer in the session (same as backup above?)

**Comment by BKDuncan** [comment]
I'll work on the messages marked in bold for the initial push. Once that is all setup and merged, then its a free-for-all for anyone who wants to take any events.

**Comment by CarolineZhou** [comment]
Regarding heartbeats, I feel like we don't have to implement that while when a client disconnects, the tracker should be able to detect that.

**Comment by CarolineZhou** [comment]
I created this doc for peer-tracker communication. I was thinking we could use this to communicate stuff such as <if a peer sends message/request "new session" to the tracker, the tracker should expect to have a json obj stringified with info such as session name and peer id> and <peer expects to receive a response "session created" with session name and session id>. What do you guys think?

**Comment by BKDuncan** [comment]
Definitely agree on heartbeats!

The doc is a good idea. Maybe we can add to the top comment so we won't have to scroll each time 😂? I think you guys are able to edit my comment.

**Comment by BKDuncan** [comment]
What do you think about this for formatting the doc?

**Message Type: `new_session`**
**Data:**
``` js
{
"session_name": "CodeCollab.cpp",
"peer_id": "a5b7gp31a"
} 
```

**Comment by CarolineZhou** [comment]
I think this format looks great! I will add what we have so far to `readme`.
